# Path to original dataset
data_path: /home/vs66tavy/Nextcloud/insect-photos-url-gbif/gbif-occurences/P1_Data

# Path to sampled dataset
path: /home/vs66tavy/Documents/P1_Data_sampled
train: /home/vs66tavy/Documents/P1_Data_sampled/train/images
val: /home/vs66tavy/Documents/P1_Data_sampled/val/images

# Path(base) to save directory
save_path: /home/vs66tavy/Documents/P1_yolov5

# Path to all yolov5 hyperparameters
hyperparms_path: /home/vs66tavy/Documents/yolov5/data/hyps/hyp.scratch-med.yaml

# Model(basic) hyperparameters
weights: yolov5s6.pt
epochs: 3
batch_size: 8
image_size: 1280

# Classes
nc: 8  # number of classes
names: [ 'Araneae', 'Coleoptera', 'Diptera', 'Hemiptera', 'Hymenoptera_Formicidae', 'Hymenoptera', 'Lepidoptera', 'Orthoptera' ]  # class names

# Verbose
# select print info 0=quiet, 1=cruicial, 2=all data info, 3=including plots
verbose: 2

# Seed
seed: 99

# ratio to split training testing and validation
traintestval_ratio: [.6, .2, .2]
